name: GitHub CI

on: [push]

defaults:
  run:
    shell: 'bash -o errexit -o nounset -o pipefail {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvmType: [jdk, jre]
        version: [8, 11, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env:
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
        run: |
          cd "${jvmType}${version}"
          docker pull "adoptopenjdk:${version}-${jvmType}-hotspot"
          docker build --tag "groovy:${jvmType}${version}" .
      - name: test
        env:
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
          expectedGroovyVersion: 4.0.0-alpha-3
        run: |
          cd test
          ./run.sh "groovy:${jvmType}${version}" "${expectedGroovyVersion}"
